import time
print('This is a message to my dumboooo')
print()
print("=" * 50)
print()
print("💕" * 15)
print()
print("        Hiiiiiiiii loveeeee! 👋")
print()
print("   Just wanted to remind you that...")
print()
time.sleep(1)
print("   ✨ You make every day brighter")
print()
time.sleep(1)
print("   💐 Your smile is my favorite thing")
print()
time.sleep(1)
print("   😋 I'm so lucky to have you")
print()


time.sleep(1)
print("   I appreciate you more than ever, and you make me the happiest ❤️")
print()
time.sleep(1)
print("   I love talking to youu hehe and thank you for being in my life. 🫵🏻️")
print()
time.sleep(1)
print("   You're my comfort zone, my home my peace hehee 🫶🏻️")
print()
time.sleep(1)
print("💕" * 15)
print()
time.sleep(1)
print(' Also before ending, you deserver all these hearts and flowers!!!! ')
time.sleep(1)
print()
print('🌹💐🌷🌸🌺🌻🌼🪷🪻')
print('❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️️')
print('🌹💐🌷🌸🌺🌻🌼🪷🪻')
print('❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️️')
print('🌹💐🌷🌸🌺🌻🌼🪷🪻')
print('❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️️')
print('🌹💐🌷🌸🌺🌻🌼🪷🪻')
print('❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️️')
print('🌹💐🌷🌸🌺🌻🌼🪷🪻')
print('❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️️')
print('🌹💐🌷🌸🌺🌻🌼🪷🪻')
print('❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️️')
print('🌹💐🌷🌸🌺🌻🌼🪷🪻')
print('❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️️')
print('🌹💐🌷🌸🌺🌻🌼🪷🪻')
print('❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️️')
print('🌹💐🌷🌸🌺🌻🌼🪷🪻')
print('❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️️')
print('🌹💐🌷🌸🌺🌻🌼🪷🪻')
print('❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️️')
print('🌹💐🌷🌸🌺🌻🌼🪷🪻')
print('❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️️')
print('🌹💐🌷🌸🌺🌻🌼🪷🪻')
print('❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️️')
print('🌹💐🌷🌸🌺🌻🌼🪷🪻')
print('❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️️')
print('🌹💐🌷🌸🌺🌻🌼🪷🪻')
print('❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️️')
print('🌹💐🌷🌸🌺🌻🌼🪷🪻')
print('❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️️')
print('🌹💐🌷🌸🌺🌻🌼🪷🪻')
print('❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️️')
print('🌹💐🌷🌸🌺🌻🌼🪷🪻')
print('❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️️')
print('🌹💐🌷🌸🌺🌻🌼🪷🪻')
print('❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️️')


print("=" * 50)

input("\nPress Enter to close...")